name: Code Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4
      - name: Cache Dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4
      - name: Unit tests
        run: make test

